#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d 1 2 3 4 5 6 7 8 9 10
~/.config/bspwm/refresh_spaces.sh

bspc config border_width  8
bspc config window_gap   30

bspc config single_monocle true
bspc config gapless_monocle true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_action1 resize_corner
bspc config pointer_action2 move

bspc config normal_border_color  \#aaaaaa
bspc config focused_border_color \#fba922

# Window rules, not working...
bspc rule -a gnome-calculator state=floating

# Fix for blank java apps.
wmname LG3D

# Startup apps.
polybar Virtual1 &
~/bin/fixmousebuttons.sh
/usr/bin/unclutter -b
/usr/bin/nm-applet &
