#! /bin/sh

# TODOs
# - dunst notification deamon, collides with regoliths rofication.
# - border color, not working

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d 1 2 3 4 5 6 7 8 9 10
~/.config/bspwm/refresh_spaces.sh

bspc config border_width         4
bspc config window_gap          12
bspc config active_border_color "#ff6600" # funkar ej...
bspc config single_monocle true
bspc config gapless_monocle true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_action1 resize_corner
bspc config pointer_action2 move

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

polybar Virtual1 &
~/bin/fixmousebuttons.sh
/usr/bin/unclutter -b
/usr/bin/nm-applet &
