#!/bin/bash

# Scale fonts
sudo cp etc/profile.d/scale_up /etc/profile.d/
cp other/Xresources ~/.Xresources

# Add .config
cp -r dot.config/* ~/.config/

# Polybar
cp -r dot.config/polybar ~/.config/
# Polybar font
mkdir -p ~/.local/share/fonts
cp dot.local/share/fonts/* ~/.local/share/fonts/

# Terminal (gnome-term + fish).
# Set my PS1. (todo check if already added)
cat other/nice_PS1 >> ~/.bashrc

# Gnome.
# Use fish for my terminal, but not as the default shell
PROFILE_PATH=/org/gnome/terminal/legacy/profiles:/:11111111-1111-1111-1111-111111111111
dconf write /org/gnome/terminal/legacy/profiles:/list "['11111111-1111-1111-1111-111111111111']"
dconf write $PROFILE_PATH/visible-name "'Solarized fish'"
dconf write $PROFILE_PATH/cursor-blink-mode "'on'"
dconf write $PROFILE_PATH/scrollback-unlimited "'true'"
dconf write $PROFILE_PATH/use-theme-colors "'false'"
dconf write $PROFILE_PATH/custom-command "'fish'"
dconf write $PROFILE_PATH/use-custom-command "'true'"
dconf write $PROFILE_PATH/background-color "'rgb(253,246,227)'"
dconf write $PROFILE_PATH/foreground-color "'rgb(101,123,131)'"
dconf write $PROFILE_PATH/palette "['rgb(7,54,66)', 'rgb(220,50,47)', 'rgb(133,153,0)', 'rgb(181,137,0)', 'rgb(38,139,210)', 'rgb(211,54,130)', 'rgb(42,161,152)', 'rgb(238,232,213)', 'rgb(0,43,54)', 'rgb(203,75,22)', 'rgb(88,110,117)', 'rgb(101,123,131)', 'rgb(131,148,150)', 'rgb(108,113,196)', 'rgb(147,161,161)', 'rgb(253,246,227)']"

## Apply theme & icons.
#gsettings set org.gnome.desktop.wm.preferences theme 'Numix'
#gsettings set org.gnome.desktop.interface gtk-theme 'Numix'
#gsettings set org.gnome.desktop.interface icon-theme 'Paper'

## Set fonts.
#dconf write /org/gnome/desktop/interface/monospace-font-name "'JetBrains Mono 10'"
#gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Noto Sans 11'
gsettings set org.gnome.desktop.interface monospace-font-name 'JetBrains Mono 10'
#gsettings set org.gnome.desktop.interface document-font-name 'Noto Sans 11'
#gsettings set org.gnome.desktop.interface font-name 'Noto Sans 11'

# Gedit
gsettings set org.gnome.gedit.preferences.editor auto-indent true
gsettings set org.gnome.gedit.preferences.editor auto-save false
gsettings set org.gnome.gedit.preferences.editor auto-save-interval uint32 10
gsettings set org.gnome.gedit.preferences.editor background-pattern 'grid'
gsettings set org.gnome.gedit.preferences.editor bracket-matching true
gsettings set org.gnome.gedit.preferences.editor create-backup-copy false
gsettings set org.gnome.gedit.preferences.editor display-line-numbers true
gsettings set org.gnome.gedit.preferences.editor display-overview-map true
gsettings set org.gnome.gedit.preferences.editor display-right-margin true
gsettings get org.gnome.gedit.preferences.editor use-default-font true
gsettings set org.gnome.gedit.preferences.editor ensure-trailing-newline true
gsettings set org.gnome.gedit.preferences.editor highlight-current-line true
gsettings set org.gnome.gedit.preferences.editor insert-spaces true
gsettings set org.gnome.gedit.preferences.editor max-undo-actions 2000
gsettings set org.gnome.gedit.preferences.editor restore-cursor-position true
gsettings set org.gnome.gedit.preferences.editor right-margin-position uint32 120
gsettings set org.gnome.gedit.preferences.editor scheme 'solarized-light'
gsettings set org.gnome.gedit.preferences.editor search-highlighting true
gsettings set org.gnome.gedit.preferences.editor smart-home-end 'after'
gsettings set org.gnome.gedit.preferences.editor syntax-highlighting true
gsettings set org.gnome.gedit.preferences.editor tabs-size uint32 4
gsettings set org.gnome.gedit.preferences.editor use-default-font false
gsettings set org.gnome.gedit.preferences.editor wrap-last-split-mode 'word'
gsettings set org.gnome.gedit.preferences.editor wrap-mode 'word'
gsettings set org.gnome.gedit.preferences.ui bottom-panel-visible false
gsettings set org.gnome.gedit.preferences.ui max-recents uint32 5
gsettings set org.gnome.gedit.preferences.ui show-tabs-mode 'auto'
gsettings set org.gnome.gedit.preferences.ui side-panel-visible false
gsettings set org.gnome.gedit.preferences.ui statusbar-visible true
gsettings set org.gnome.gedit.preferences.ui toolbar-visible true


