#!/bin/bash

sudo apt update
sudo apt -y upgrade

# Regolith
#sudo add-apt-repository -y ppa:regolith-linux/release
#sudo apt -y install regolith-desktop-complete

# Desktop environment
sudo apt -y install bspwm polybar suckless-tools thunar gedit ranger highlight gnome-terminal gnome-tweaks fish


# Hardware support
sudo apt -y install powertop xbacklight
# Touchpad
sudo apt -y install ruby xdotool libinput-tools
sudo gem i fusuma


# Standard packages
# Terminator? mousepad? sudo snap install gotop?
#archivemanager?
#image viewer
#screenshot
#startup disk creator
sudo apt -y install gnome-calculator tree gnome-system-monitor vivaldi-stable usb-creator-gtk 


# Chrome browser
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg --install google-chrome-stable_current_amd64.deb


# Development tools
sudo apt -y install openjdk-8-jdk openjdk-17-jdk virtualbox curl jq maven git
sudo snap install --classic intellij-idea-community
#sudo snap install --classic intellij-idea-ultimate
sudo snap install --classic code
sudo snap install --classic node
sudo npm install -g @angular/cli


# Looks
sudo apt -y install fonts-jetbrains-mono

