#!/bin/bash

sudo apt update
sudp apt -y upgrade

# Regolith
sudo add-apt-repository -y ppa:regolith-linux/release
sudo apt -y install regolith-desktop-complete

# Standard packages
# Terminator? mousepad? sudo snap install gotop?
#archivemanager?
#image viewer
#screenshot
#startup disk creator
sudo apt -y install polybar highlight ranger gnome-terminal thunar gedit gnome-tweaks gnome-calculator tree gnome-system-monitor powertop

# Chrome browser
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg --install google-chrome-stable_current_amd64.deb


# Development tools
sudo apt -y install openjdk-8-jdk openjdk-15-jdk virtualbox curl jq maven npm git
sudo snap install --classic intellij-idea-community
#sudo snap install --classic intellij-idea-ultimate

#curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
#sudo apt install -y nodejs
#sudo snap install node --channel=14/stable --classic
sudo npm install -g @angular/cli


# Insync
echo "INSTALL INSYNC MANUALLY..."

# Looks...
#sudo apt -y install  numix-gtk-theme numix-icon-theme
echo "INSTALL FONTS..."

