#!/bin/bash

# Regolith - i3 desktop
sudo add-apt-repository -y ppa:kgilmer/regolith-stable
sudo apt -y install regolith-desktop


# Polybar
## build tools, etc.
sudo apt -y install build-essential git cmake cmake-data pkg-config python3-sphinx libcairo2-dev libxcb1-dev libxcb-util0-dev libxcb-randr0-dev libxcb-composite0-dev python-xcbgen xcb-proto libxcb-image0-dev libxcb-ewmh-dev libxcb-icccm4-dev

sudo apt -y install curl jq

## plugin stuff
sudo apt -y install libxcb-xkb-dev libxcb-xrm-dev libxcb-cursor-dev libpulse-dev libjsoncpp-dev libcurl4-openssl-dev libnl-genl-3-dev

## get & build release
mkdir ~/bin
pushd ~/bin
#wget https://github.com/jaagr/polybar/releases/download/3.4.0/polybar-3.4.0.tar
curl https://api.github.com/repos/polybar/polybar/releases/latest | jq -r .assets[0].browser_download_url | wget -qi -

tar xvf polybar-*.tar
cd polybar 
mkdir build 
pushd build
cmake ..
make -j$(nproc)
sudo make install
popd
popd



# Looks...
sudo apt -y install  numix-gtk-theme numix-icon-theme
echo "INSTALL FONTS..."



# Some essential tools
sudo apt -y install ranger terminator thunar mousepad gedit gnome-tweaks gnome-calculator tree gnome-system-monitor powertop
sudo snap install gotop

#archivemanager?
#image viewer
#screenshot
#startup disk creator



# Chrome browser
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg --install google-chrome-stable_current_amd64.deb



# Insync
echo "INSTALL INSYNC MANUALLY..."



# Development tools
sudo apt -y install openjdk-8-jdk openjdk-13-jdk virtualbox curl jq maven npm
#sudo snap install --classic intellij-idea-community
sudo snap install --classic intellij-idea-ultimate

curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
sudo apt install -y nodejs

sudo npm install -g @angular/cli

