#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Set spaces names
~/.config/bspwm/refresh_spaces.sh

# Configure bspwm
bspc config border_width  8
bspc config window_gap   30

bspc config single_monocle true
bspc config gapless_monocle true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_action1 resize_corner
bspc config pointer_action2 move

bspc config normal_border_color  \#aaaaaa
bspc config focused_border_color \#fba922

bspc rule -a gnome-calculator state=floating

# Fix for blank java apps.
wmname LG3D

# bgcolor and cursor
xsetroot -solid "#888888" &
xsetroot -cursor_name left_ptr &

# Startup apps.
polybar top &
/usr/bin/unclutter -b &
/usr/bin/nm-applet &
fusuma -d &

# Somehow the super-space shortcut only works after a reload. So let's reload.
sleep 1
pkill -USR1 -x sxhkd &

/usr/bin/setxkbmap -layout gb -variant shift-for-numbers
