#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

~/.config/bspwm/refresh_spaces.sh

bspc config border_width  8
bspc config window_gap   30

bspc config single_monocle true
bspc config gapless_monocle true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_action1 resize_corner
bspc config pointer_action2 move

bspc config normal_border_color  \#aaaaaa
bspc config focused_border_color \#fba922

# Window rules, not working...
bspc rule -a gnome-calculator state=floating

# Fix for blank java apps.
wmname LG3D

# Startup apps.
polybar top &
/usr/sbin/fixmousebuttons.sh
/usr/bin/unclutter -b
/usr/bin/nm-applet &
xsetroot -cursor_name left_ptr &


# Scale down gui (this is too laggy...)
#( sleep 10 ; xrandr --output $(xrandr --query | grep " connected" | awk '{print $1}') --scale '1.14x1.14' ) &

# bgcolor
xsetroot -solid "#888888"
