#! /bin/sh

start() {
    pgrep -x $1 > /dev/null || $1 $2 $3 $4 &
}

start sxhkd

# Configure bspwm
bspc config border_width  8
bspc config window_gap   30

bspc config single_monocle true
bspc config gapless_monocle true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_action1 resize_corner
bspc config pointer_action2 move

bspc config normal_border_color  \#aaaaaa
bspc config focused_border_color \#fba922

bspc rule -a gnome-calculator state=floating

# Fix for blank java apps.
wmname LG3D

# bgcolor and cursor
xsetroot -solid "#888888" &
xsetroot -cursor_name left_ptr &
#unclutter -b

# Set spaces names
bash ~/.config/bspwm/refresh_spaces.sh

# Polybar
killall polybar
polybar bar1 &
polybar bar2 &
polybar bar3 &

# Startup apps.
start nm-applet
start fusuma -d
start redshift-gtk

# Somehow the super-space shortcut only works after a reload. So let's reload.
sleep 1
pkill -USR1 -x sxhkd &

setxkbmap -layout gb -variant shift-for-numbers
