- name: Install packages for unattended upgrades
  become: true
  ansible.builtin.package:
    name: 
      - unattended-upgrades
      - mailutils
    state: present

- name: Enable unattended upgrades
  become: true
  ansible.builtin.copy:
    mode: '0644'
    src: "files/{{ item }}"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
  with_items:
    - 20auto-upgrades
    - 50unattended-upgrades
