
- name: Install hardware support
  become: true
  ansible.builtin.package:
    name: 
      - powertop
      - xserver-xorg-input-synaptics
      - ruby # get gem, for next step.
      - libinput-tools
    state: present

# TODO this does not work...
- name: Install hardware support, from gem
  become: true
  community.general.gem:
    name: fusuma
    version: 1.0
    state: present

- name: Fix intel graphics issues
  become: true
  ansible.builtin.copy:
    src: files/20-intel.conf
    dest: /etc/X11/xorg.conf.d/

- name: Add fusuma config, for multitouch mousepad
  ansible.builtin.copy:
    src: files/fusuma.yml
    dest: ~/.config/fusuma/config.yml

- name: Add script for fixing mouse button behaviour
  become: true
  ansible.builtin.copy:
    src: files/fixmousebuttons.sh
    dest: /usr/sbin/
    mode: '0755'

- name: Add user '{{ ansible_env.USER }}' to group 'input', for fusuma
  become: true
  user:
    name: '{{ ansible_env.USER }}'
    groups: input
    append: yes

- name: Do not autostart bluetooth
  become: true
  ansible.builtin.lineinfile:
    path: /etc/bluetooth/main.conf
    regexp: '^AutoEnable=.*'
    line: AutoEnable=false
