Vagrant.configure("2") do |config|
    config.vm.box = "bento/fedora-latest"
    # config.vm.box = "ubuntu/mantic64"

    config.vm.synced_folder "../", "/home/vagrant/linux_config"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "Fedora vagrant"
        
        vb.gui = true

        vb.cpus = 4
        vb.memory = "8192"

        # Graphic memory
        vb.customize ["modifyvm", :id, "--vram", "128"]

        vb.customize ["modifyvm", :id, "--monitorcount", "2"]

    end
    config.vm.provision "shell", inline: <<-SHELL
        dnf -y upgrade
        dnf -y group install "Fedora Workstation"
        systemctl set-default graphical.target
        # systemctl enable gdm --now

        # sudo apt-add-repository multiverse
        # sudo apt update
        # sudo apt install -y --no-install-recommends ubuntu-desktop-minimal
        # sudo apt install -y --no-install-recommends virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11
        # sudo reboot

    SHELL

end