- name: Copy .config folders
  ansible.builtin.copy:
    src: "files/{{ item }}/"
    dest: "~/.config/{{ item }}/"
    mode: '0755'
  with_items:
    - bat
    - bspwm
    - dunst
    - fish
    - kitty
    - polybar
    - sxhkd
    - Thunar

- name: Copy redshift config file
  ansible.builtin.copy:
    src: "files/redshift/redshift.conf"
    dest: "~/.config/redshift.conf"
    mode: '0644'

- name: Copy nano config file
  ansible.builtin.copy:
    src: "files/nano/nanorc"
    dest: "~/.nanorc"
    mode: '0644'

- name: Make files executable
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0744'
  with_items:
    - ~/.config/bspwm/bspwmrc
    - ~/.config/bspwm/refresh_spaces.sh
    - ~/.config/sxhkd/rofi-system-menu.sh

- name: Add iosevka icon font
  ansible.builtin.copy:
    src: files/fonts/iosevka_nerd_font.ttf
    dest: ~/.local/share/fonts/
    mode: '0644'
