- name: Copy .config folders
  ansible.builtin.copy:
    src: "files/{{ item }}/"
    dest: "~/.config/{{ item }}/"
    mode: '0755'
  with_items:
    - bat
   # - fish
    - kitty
    - sway
    - Thunar
    - waybar

- name: Copy nano config file
  ansible.builtin.copy:
    src: "files/nano/nanorc"
    dest: "~/.nanorc"
    mode: '0644'

- name: Make files executable
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0744'
  with_items:
    - ~/.config/sway/scripts/lock-screen.sh
    - ~/.config/sway/scripts/rename_workspace.sh
    - ~/.config/waybar/scripts/get_layout.sh
    - ~/.config/waybar/scripts/get_cpugovernor.sh
    - ~/.config/waybar/scripts/toggle_cpugovernor.sh

# - name: Add iosevka icon font
#   ansible.builtin.copy:
#     src: files/fonts/iosevka_nerd_font.ttf
#     dest: ~/.local/share/fonts/
#     mode: '0644'
