
- name: Set DPI for browsers
  ansible.builtin.copy:
    src: files/font-size/Xresources
    dest: ~/.Xresources

- name: Set font scaling for GTK and QT apps
  become: true
  ansible.builtin.copy:
    src: files/font-size/font_scaling
    dest: /etc/profile.d/
