- name: Install base packages
  become: true
  ansible.builtin.package:
    name:
      - sway
      - swayidle
      - swaylock
      - python3-i3ipc
      - waybar
      - fontawesome-fonts-all

      - rofi # replace with fuzzle ?
      - mako

      - wlsunset
      - wtype
      - grim
      - ffmpeg-free
      - brightnessctl

      - jetbrains-mono-fonts

      - kitty
      - fastfetch
    state: present

- name: Install cli tools
  become: true
  ansible.builtin.package:
    name:
      - fish
      - ranger
      - bat
      - tree
      - fastfetch
    state: present

# - name: Add Vivaldi repository
#   become: true
#   ansible.builtin.yum_repository:
#     name: vivaldi
#     description: Vivaldi
#     baseurl: https://repo.vivaldi.com/archive/rpm/{{ ansible_architecture }}
#     gpgkey: https://repo.vivaldi.com/archive/linux_signing_key.pub

- name: Add Brave repository
  become: true
  ansible.builtin.yum_repository:
    name: brave
    description: Brave
    baseurl: https://brave-browser-rpm-release.s3.brave.com/$basearch
    gpgkey: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

- name: Install applications
  become: true
  ansible.builtin.package:
    name:
      - gedit
      - gnome-calculator
      - gnome-screenshot
      - gnome-system-monitor
      - gnome-terminal
      - gnome-tweaks
      - thunar
      - thunar-archive-plugin
      - mediawriter
      - chromium-browser
      # - vivaldi-stable
      - brave-browser
    state: present
