- name: Install base packages
  become: true
  ansible.builtin.package:
    name: 
      - bspwm
      - polybar
      - rofi
      - xdotool
      - dunst
      - redshift-gtk
    state: present

- name: Install base packages (ubuntu)
  become: true
  ansible.builtin.package:
    name: 
      - x11-xserver-utils
      - suckless-tools
      - fonts-jetbrains-mono
    state: present
  when:
    - ansible_facts['distribution'] == "Ubuntu"

- name: Install base packages (fedora)
  become: true
  ansible.builtin.package:
    name: 
      - xsetroot
      - wmname
      - jetbrains-mono-fonts
    state: present
  when:
    - ansible_facts['distribution'] == "Fedora"

- name: Install cli tools
  become: true
  ansible.builtin.package:
    name: 
      - fish
      - ranger
      - bat
      - tree
    state: present

- name: Import Vivaldi APT repo keys
  become: true
  apt_key:
    url: https://repo.vivaldi.com/archive/linux_signing_key.pub
  when:
    - ansible_facts['distribution'] == "Ubuntu"

- name: Add Vivaldi APT repositories
  become: true
  apt_repository:
    repo: deb https://repo.vivaldi.com/archive/deb/ stable main
    filename: vivaldi-stable
  when:
    - ansible_facts['distribution'] == "Ubuntu"

- name: Install applications
  become: true
  ansible.builtin.package:
    name: 
      - gedit
      - gnome-calculator
      - gnome-screenshot
      - gnome-system-monitor
      - gnome-terminal
      - gnome-tweaks
      - thunar
    state: present

- name: Install applications (ubuntu)
  become: true
  ansible.builtin.package:
    name: 
      - chromium-browser
      - dconf-cli
      - usb-creator-gtk
      - vivaldi-stable 
    state: present
  when:
    - ansible_facts['distribution'] == "Ubuntu"

- name: Install applications (fedora)
  become: true
  ansible.builtin.package:
    name: 
      - chromium
    state: present
  when:
    - ansible_facts['distribution'] == "Fedora"

- ansible.builtin.import_tasks:
    file: font-size.yaml

- ansible.builtin.import_tasks:
    file: copy-config-files.yaml

- ansible.builtin.import_tasks:
    file: look-n-feel.yaml
