
- name: Install software
  ansible.builtin.import_tasks:
    file: install.yaml

- name: System settings
  ansible.builtin.import_tasks:
    file: system-settings.yaml

- name: Font size
  ansible.builtin.import_tasks:
    file: font-size.yaml

- name: Copy config
  ansible.builtin.import_tasks:
    file: copy-config-files.yaml

- name: Set look n feel
  ansible.builtin.import_tasks:
    file: look-n-feel.yaml
