
- name: Install PIP
  become: true
  ansible.builtin.package:
    name: python3-pip

- name: Install gext, 
  ansible.builtin.pip:
    name: gnome-extensions-cli
    extra_args: --user --upgrade

- name: Install gnome extension PaperWM
  ansible.builtin.command:
    cmd: /home/markus/.local/bin/gext install "paperwm@paperwm.github.com" gext enable "paperwm@paperwm.github.com"

- name: Install gnome extension Astra monitor
  ansible.builtin.command:
    cmd: /home/markus/.local/bin/gext install "monitor@astraext.github.io" gext enable "monitor@astraext.github.io"

