- name: Install developer tools, from package manager
  become: true
  ansible.builtin.package:
    name:
      - git
      - openjdk-8-jdk
      - openjdk-21-jdk
      - maven
      - virtualbox
      # - vagrant
      - curl
      - jq
      - ansible-lint
    state: present

- name: Install developer tools, from snap
  become: true
  community.general.snap:
    name:
      - intellij-idea-ultimate
      - code
      - node
      - mqtt-explorer
    classic: true

- name: Install developer tools, from npm
  become: true
  community.general.npm:
    name: "@angular/cli"
    global: true
    state: present

- name: Import docker apt repo keys
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add docker apt repositories
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_facts.lsb.codename }} stable
    filename: docker

- name: Install docker
  become: true
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Configure docker
  become: true
  ansible.builtin.copy:
    content: '{ "features": { "buildkit": true } }'
    dest: /etc/docker/daemon.json
    mode: '0644'

- name: Add user '{{ ansible_env.USER }}' to group 'docker'
  become: true
  ansible.builtin.user:
    name: '{{ ansible_env.USER }}'
    groups: docker
    append: true
